# ====================================================================================
# Setup Project


# ====================================================================================
# Actions

.PHONY: py.setup
py.setup: #! Install the pip dependency.
	python3 -m pip install --user --disable-pip-version-check -r requirements.txt

.PHONY: py.build
py.build: #! Do nothing.
	@:

.PHONY: py.run
py.run: #! Run the application.
	python3 $(PROJECT_FOLDER)main.py

.PHONY: py.test
py.test: #! Run all the unit test on the codebase.
	python3 -m unittest discover

.PHONY: py.coverage
py.coverage: #! Run the unit test and generate the coverage report
	coverage run --source=$(PROJECT_FOLDER) -m unittest discover
	coverage html
	coverage report -m

.PHONY: py.docs
py.docs: #! Run pdoc to auto-generates API documentation
	pdoc --html --force --output-dir $(DOC_FOLDER) $(PROJECT_FOLDER)
	mv $(DOC_FOLDER)/$(PROJECT_FOLDER)/* $(DOC_FOLDER)
	rmdir $(DOC_FOLDER)/$(PROJECT_FOLDER)

.PHONY: .py.clean
py.clean: #! Remove autogenerated file
	rm .coverage || true
	rm -r htmlcov/ || true
	rm .mypy_cache || true

